# Generated by Django 6.1 on 2026-08-25 17:14

import infraestructura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoservidor',
            name='direccion_ip',
            field=models.GenericIPAddressField(help_text='Debe pertenecer a una subred corporativa autorizada (10.10.0.0/16, 10.20.0.0/16, 172.16.8.0/22).', validators=[infraestructura.models.validar_ip_corporativa], verbose_name='Dirección IP'),
        ),
    ]
