# Generated by Django 6.1 on 2026-08-29 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0002_alter_nodoservidor_direccion_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(verbose_name='Detalle del Evento')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='infraestructura.nodoservidor', verbose_name='Servidor Afectado')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Historial de Auditoría',
                'ordering': ('-fecha_evento',),
            },
        ),
    ]
