/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auditorias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Bitácora de auditoría de toda la flota.
         *
         *     Se permite crear registros (para que un agente externo pueda reportar
         *     eventos), pero no editarlos ni borrarlos: una bitácora que se puede
         *     reescribir a posteriori no sirve como evidencia. De ahí que
         *     http_method_names recorte PUT/PATCH/DELETE en lugar de dejar el
         *     ModelViewSet completo.
         */
        get: operations["auditorias_list"];
        put?: never;
        /**
         * @description Bitácora de auditoría de toda la flota.
         *
         *     Se permite crear registros (para que un agente externo pueda reportar
         *     eventos), pero no editarlos ni borrarlos: una bitácora que se puede
         *     reescribir a posteriori no sirve como evidencia. De ahí que
         *     http_method_names recorte PUT/PATCH/DELETE en lugar de dejar el
         *     ModelViewSet completo.
         */
        post: operations["auditorias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Bitácora de auditoría de toda la flota.
         *
         *     Se permite crear registros (para que un agente externo pueda reportar
         *     eventos), pero no editarlos ni borrarlos: una bitácora que se puede
         *     reescribir a posteriori no sirve como evidencia. De ahí que
         *     http_method_names recorte PUT/PATCH/DELETE en lugar de dejar el
         *     ModelViewSet completo.
         */
        get: operations["auditorias_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidencias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        get: operations["incidencias_list"];
        put?: never;
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        post: operations["incidencias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidencias/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        get: operations["incidencias_retrieve"];
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        put: operations["incidencias_update"];
        post?: never;
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        delete: operations["incidencias_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD de incidencias más la acción de cierre.
         *
         *     Recordar que el serializer marca 'estado' y 'fecha_resolucion' como de
         *     solo lectura: el ciclo de vida se mueve únicamente por la acción
         *     resolver(), nunca por un PATCH directo del campo.
         */
        patch: operations["incidencias_partial_update"];
        trace?: never;
    };
    "/api/incidencias/{id}/resolver/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cierra la incidencia: la pasa a 'resuelta' y sella la fecha. */
        post: operations["incidencias_resolver_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mantenimientos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        get: operations["mantenimientos_list"];
        put?: never;
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        post: operations["mantenimientos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mantenimientos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        get: operations["mantenimientos_retrieve"];
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        put: operations["mantenimientos_update"];
        post?: never;
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        delete: operations["mantenimientos_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD de la agenda de mantenimientos.
         *
         *     Es el equivalente en API del CRUD con Vistas Basadas en Clases de
         *     views.py: lo que allí son cinco clases (MantenimientoListView,
         *     DetailView, CreateView, UpdateView, DeleteView) aquí cabe en un solo
         *     ModelViewSet, porque las cinco operaciones comparten modelo y
         *     serializer y solo se distinguen por el verbo HTTP.
         */
        patch: operations["mantenimientos_partial_update"];
        trace?: never;
    };
    "/api/servidores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD completo de la flota de servidores. */
        get: operations["servidores_list"];
        put?: never;
        /** @description CRUD completo de la flota de servidores. */
        post: operations["servidores_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servidores/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD completo de la flota de servidores. */
        get: operations["servidores_retrieve"];
        /** @description CRUD completo de la flota de servidores. */
        put: operations["servidores_update"];
        post?: never;
        /** @description CRUD completo de la flota de servidores. */
        delete: operations["servidores_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD completo de la flota de servidores. */
        patch: operations["servidores_partial_update"];
        trace?: never;
    };
    "/api/servidores/{id}/auditorias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bitácora del nodo, paginada e independiente de su ficha. */
        get: operations["servidores_auditorias_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servidores/{id}/incidencias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Incidencias del nodo; admite ?estado=abierta|resuelta. */
        get: operations["servidores_incidencias_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servidores/{id}/mantenimientos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Agenda del nodo; admite ?completado=true|false. */
        get: operations["servidores_mantenimientos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `abierta` - Abierta
         *     * `resuelta` - Resuelta
         * @enum {string}
         */
        EstadoEnum: "abierta" | "resuelta";
        /**
         * @description Incidencias operativas de un nodo.
         *
         *     'estado' y 'fecha_resolucion' quedan como read_only por la misma razón
         *     por la que IncidenciaServidorForm los excluye de sus fields: una
         *     incidencia nace siempre 'abierta' y se cierra mediante una acción
         *     explícita (POST /api/incidencias/<id>/resolver/), no editando el campo
         *     a mano. Así el sellado de fecha_resolucion nunca queda a criterio del
         *     cliente y no puede haber una incidencia 'resuelta' sin fecha.
         */
        IncidenciaServidor: {
            readonly id: number;
            /** Servidor Afectado */
            servidor: number;
            readonly servidor_hostname: string;
            /** Título */
            titulo: string;
            /** Descripción del Fallo */
            descripcion: string;
            severidad?: components["schemas"]["SeveridadEnum"];
            readonly severidad_display: string;
            /** Estado de Resolución */
            readonly estado: components["schemas"]["EstadoEnum"];
            readonly estado_display: string;
            /**
             * Fecha de Reporte
             * Format: date-time
             */
            readonly fecha_reporte: string;
            /**
             * Fecha de Resolución
             * Format: date-time
             */
            readonly fecha_resolucion: string | null;
        };
        /**
         * @description Tareas de mantenimiento programadas sobre un nodo.
         *
         *     Aquí no hay campos de solo lectura más allá del id, al revés que en
         *     IncidenciaServidorSerializer: 'fecha_programada' la fija el operador al
         *     planificar la ventana (por eso el modelo no usa auto_now_add) y
         *     'completado' se marca con un PATCH normal cuando la tarea se ejecuta.
         *     No hace falta una @action como resolver() porque al cerrar un
         *     mantenimiento no queda ninguna fecha que sellar.
         */
        MantenimientoNodo: {
            readonly id: number;
            /** Servidor Asignado */
            servidor: number;
            readonly servidor_hostname: string;
            /** Título del Mantenimiento */
            titulo_tarea: string;
            /** Descripción de la Tarea */
            descripcion_tecnica: string;
            /** Tipo de Tarea */
            tipo?: components["schemas"]["TipoEnum"];
            readonly tipo_display: string;
            /** ¿Tarea Ejecutada? */
            completado?: boolean;
            /**
             * Fecha y Hora Programada
             * Format: date-time
             */
            fecha_programada: string;
        };
        /**
         * @description * `docker` - Docker
         *     * `podman` - Podman
         *     * `lxc` - LXC Linux Containers
         *     * `ninguno` - Sin contenedores
         * @enum {string}
         */
        MotorContenedoresEnum: "docker" | "podman" | "lxc" | "ninguno";
        /** @description Representación de un nodo para los listados de la API. */
        NodoServidor: {
            readonly id: number;
            /** Hostname */
            nombre_host: string;
            /**
             * Dirección IP
             * @description Debe pertenecer a una subred corporativa autorizada (10.10.0.0/16, 10.20.0.0/16, 172.16.8.0/22).
             */
            direccion_ip: string;
            /** Motor de Contenedores */
            motor_contenedores?: components["schemas"]["MotorContenedoresEnum"];
            readonly motor_contenedores_display: string;
            /** ¿Enrutado por Nginx? */
            proxy_inverso?: boolean;
            /** Estado Producción */
            en_produccion?: boolean;
            /** Format: date-time */
            readonly fecha_despliegue: string;
            readonly incidencias_abiertas: number;
        };
        /**
         * @description Ficha completa de un nodo: el equivalente en API de detalleServidor().
         *
         *     Anida la bitácora y las incidencias del nodo (ambas de solo lectura)
         *     para que el detalle se resuelva en una sola petición, igual que la
         *     plantilla detalle.html las recibe juntas en su contexto. El listado
         *     general no las incluye porque haría enorme cada página de resultados.
         */
        NodoServidorDetalle: {
            readonly id: number;
            /** Hostname */
            nombre_host: string;
            /**
             * Dirección IP
             * @description Debe pertenecer a una subred corporativa autorizada (10.10.0.0/16, 10.20.0.0/16, 172.16.8.0/22).
             */
            direccion_ip: string;
            /** Motor de Contenedores */
            motor_contenedores?: components["schemas"]["MotorContenedoresEnum"];
            readonly motor_contenedores_display: string;
            /** ¿Enrutado por Nginx? */
            proxy_inverso?: boolean;
            /** Estado Producción */
            en_produccion?: boolean;
            /** Format: date-time */
            readonly fecha_despliegue: string;
            readonly incidencias_abiertas: number;
            readonly auditorias: components["schemas"]["RegistroAuditoria"][];
            readonly incidencias: components["schemas"]["IncidenciaServidor"][];
        };
        PaginatedIncidenciaServidorList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IncidenciaServidor"][];
        };
        PaginatedMantenimientoNodoList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MantenimientoNodo"][];
        };
        PaginatedNodoServidorList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["NodoServidor"][];
        };
        PaginatedRegistroAuditoriaList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RegistroAuditoria"][];
        };
        /**
         * @description Incidencias operativas de un nodo.
         *
         *     'estado' y 'fecha_resolucion' quedan como read_only por la misma razón
         *     por la que IncidenciaServidorForm los excluye de sus fields: una
         *     incidencia nace siempre 'abierta' y se cierra mediante una acción
         *     explícita (POST /api/incidencias/<id>/resolver/), no editando el campo
         *     a mano. Así el sellado de fecha_resolucion nunca queda a criterio del
         *     cliente y no puede haber una incidencia 'resuelta' sin fecha.
         */
        PatchedIncidenciaServidor: {
            readonly id?: number;
            /** Servidor Afectado */
            servidor?: number;
            readonly servidor_hostname?: string;
            /** Título */
            titulo?: string;
            /** Descripción del Fallo */
            descripcion?: string;
            severidad?: components["schemas"]["SeveridadEnum"];
            readonly severidad_display?: string;
            /** Estado de Resolución */
            readonly estado?: components["schemas"]["EstadoEnum"];
            readonly estado_display?: string;
            /**
             * Fecha de Reporte
             * Format: date-time
             */
            readonly fecha_reporte?: string;
            /**
             * Fecha de Resolución
             * Format: date-time
             */
            readonly fecha_resolucion?: string | null;
        };
        /**
         * @description Tareas de mantenimiento programadas sobre un nodo.
         *
         *     Aquí no hay campos de solo lectura más allá del id, al revés que en
         *     IncidenciaServidorSerializer: 'fecha_programada' la fija el operador al
         *     planificar la ventana (por eso el modelo no usa auto_now_add) y
         *     'completado' se marca con un PATCH normal cuando la tarea se ejecuta.
         *     No hace falta una @action como resolver() porque al cerrar un
         *     mantenimiento no queda ninguna fecha que sellar.
         */
        PatchedMantenimientoNodo: {
            readonly id?: number;
            /** Servidor Asignado */
            servidor?: number;
            readonly servidor_hostname?: string;
            /** Título del Mantenimiento */
            titulo_tarea?: string;
            /** Descripción de la Tarea */
            descripcion_tecnica?: string;
            /** Tipo de Tarea */
            tipo?: components["schemas"]["TipoEnum"];
            readonly tipo_display?: string;
            /** ¿Tarea Ejecutada? */
            completado?: boolean;
            /**
             * Fecha y Hora Programada
             * Format: date-time
             */
            fecha_programada?: string;
        };
        /** @description Representación de un nodo para los listados de la API. */
        PatchedNodoServidor: {
            readonly id?: number;
            /** Hostname */
            nombre_host?: string;
            /**
             * Dirección IP
             * @description Debe pertenecer a una subred corporativa autorizada (10.10.0.0/16, 10.20.0.0/16, 172.16.8.0/22).
             */
            direccion_ip?: string;
            /** Motor de Contenedores */
            motor_contenedores?: components["schemas"]["MotorContenedoresEnum"];
            readonly motor_contenedores_display?: string;
            /** ¿Enrutado por Nginx? */
            proxy_inverso?: boolean;
            /** Estado Producción */
            en_produccion?: boolean;
            /** Format: date-time */
            readonly fecha_despliegue?: string;
            readonly incidencias_abiertas?: number;
        };
        /**
         * @description Bitácora de eventos de un nodo.
         *
         *     Los campos con auto_now_add (fecha_evento) los marca DRF como de solo
         *     lectura automáticamente: no se pueden enviar en el POST.
         */
        RegistroAuditoria: {
            readonly id: number;
            /** Servidor Afectado */
            servidor: number;
            readonly servidor_hostname: string;
            /** Detalle del Evento */
            detalles: string;
            /**
             * Fecha del Evento
             * Format: date-time
             */
            readonly fecha_evento: string;
        };
        /**
         * @description * `baja` - Baja
         *     * `media` - Media
         *     * `alta` - Alta
         *     * `critica` - Crítica
         * @enum {string}
         */
        SeveridadEnum: "baja" | "media" | "alta" | "critica";
        /**
         * @description * `actualizacion` - Actualización de Sistema
         *     * `backup` - Respaldo de Base de Datos
         *     * `seguridad` - Parche de Seguridad
         *     * `hardware` - Revisión de Hardware
         * @enum {string}
         */
        TipoEnum: "actualizacion" | "backup" | "seguridad" | "hardware";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auditorias_list: {
        parameters: {
            query?: {
                /** @description Qué campo usar para ordenar los resultados. */
                ordering?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRegistroAuditoriaList"];
                };
            };
        };
    };
    auditorias_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroAuditoria"];
                "application/x-www-form-urlencoded": components["schemas"]["RegistroAuditoria"];
                "multipart/form-data": components["schemas"]["RegistroAuditoria"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroAuditoria"];
                };
            };
        };
    };
    auditorias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Registro de Auditoría. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroAuditoria"];
                };
            };
        };
    };
    incidencias_list: {
        parameters: {
            query?: {
                /** @description Qué campo usar para ordenar los resultados. */
                ordering?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIncidenciaServidorList"];
                };
            };
        };
    };
    incidencias_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidenciaServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["IncidenciaServidor"];
                "multipart/form-data": components["schemas"]["IncidenciaServidor"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciaServidor"];
                };
            };
        };
    };
    incidencias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Incidencia de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciaServidor"];
                };
            };
        };
    };
    incidencias_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Incidencia de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidenciaServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["IncidenciaServidor"];
                "multipart/form-data": components["schemas"]["IncidenciaServidor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciaServidor"];
                };
            };
        };
    };
    incidencias_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Incidencia de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    incidencias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Incidencia de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIncidenciaServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIncidenciaServidor"];
                "multipart/form-data": components["schemas"]["PatchedIncidenciaServidor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciaServidor"];
                };
            };
        };
    };
    incidencias_resolver_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Incidencia de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidenciaServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["IncidenciaServidor"];
                "multipart/form-data": components["schemas"]["IncidenciaServidor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidenciaServidor"];
                };
            };
        };
    };
    mantenimientos_list: {
        parameters: {
            query?: {
                /** @description Qué campo usar para ordenar los resultados. */
                ordering?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMantenimientoNodoList"];
                };
            };
        };
    };
    mantenimientos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MantenimientoNodo"];
                "application/x-www-form-urlencoded": components["schemas"]["MantenimientoNodo"];
                "multipart/form-data": components["schemas"]["MantenimientoNodo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoNodo"];
                };
            };
        };
    };
    mantenimientos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Mantenimiento de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoNodo"];
                };
            };
        };
    };
    mantenimientos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Mantenimiento de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MantenimientoNodo"];
                "application/x-www-form-urlencoded": components["schemas"]["MantenimientoNodo"];
                "multipart/form-data": components["schemas"]["MantenimientoNodo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoNodo"];
                };
            };
        };
    };
    mantenimientos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Mantenimiento de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mantenimientos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Mantenimiento de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMantenimientoNodo"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMantenimientoNodo"];
                "multipart/form-data": components["schemas"]["PatchedMantenimientoNodo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MantenimientoNodo"];
                };
            };
        };
    };
    servidores_list: {
        parameters: {
            query?: {
                /** @description Qué campo usar para ordenar los resultados. */
                ordering?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Un término de búsqueda. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNodoServidorList"];
                };
            };
        };
    };
    servidores_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodoServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["NodoServidor"];
                "multipart/form-data": components["schemas"]["NodoServidor"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    servidores_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidorDetalle"];
                };
            };
        };
    };
    servidores_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodoServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["NodoServidor"];
                "multipart/form-data": components["schemas"]["NodoServidor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    servidores_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    servidores_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNodoServidor"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNodoServidor"];
                "multipart/form-data": components["schemas"]["PatchedNodoServidor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    servidores_auditorias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    servidores_incidencias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    servidores_mantenimientos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este Nodo de Servidor. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodoServidor"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
}
